<?php
$analysis=array(
array("name"=>"推荐线路","url"=>"https://api.qianqi.net/?url="),
array("name"=>"无广告1","url"=>"https://jx.htv009.com/?url="),
array("name"=>"无广告2","url"=>"http://api.3jx.top/vip/?url="),
array("name"=>"无广告3","url"=>"https://www.91jxs.com/jiexi/?url="),
array("name"=>"无广告4","url"=>"http://www.600m.net/jx/jx1.php?url="),
array("name"=>"兴源解析","url"=>"https://parse.xymov.net/?v="),
array("name"=>"600M","url"=>"http://www.600m.net/jx/?url="),
array("name"=>"菜鸟解析","url"=>"https://jiexi.bm6ig.cn/?url="),
array("name"=>"福星解析","url"=>"https://jx.fuxing56.com/jiexi/?url="),
array("name"=>"金桥解析","url"=>"http://jqaaa.com/jx.php?url="),
array("name"=>"H8解析","url"=>"https://www.h8jx.com/api.php?url="),
array("name"=>"黑云解析","url"=>"http://dhyjiexi.arpps.com/?url="),
array("name"=>"云解析","url"=>"http://openapi.pinjun66.com/Yun.php?url="),
array("name"=>"600e","url"=>"https://660e.com/?url="),
array("name"=>"8090g","url"=>"https://www.8090g.cn/index.php?url="),
array("name"=>"618解析","url"=>"https://jx.618g.com/?url="),
array("name"=>"1717云","url"=>"http://www.1717yun.com/jx/ty.php?url="),
array("name"=>"1907TV","url"=>"https://z1.m1907.cn/?jx="),
array("name"=>"思古","url"=>"https://jsap.attakids.com/?url=")
)
?>